#!/bin/sh
set -eu
if [ "$(id -u)" -ne 0 ]; then exec sudo "$0" "$@"; fi
cat > /etc/modprobe.d/note-nvidia-kms.conf <<'CONF'
options nvidia_drm modeset=1 fbdev=1
CONF
update-initramfs -u
printf 'NVIDIA DRM KMS habilitado. Reinicia el sistema.\n'
