#!/bin/sh
set -eu

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=note
export XDG_CURRENT_DESKTOP=Note:labwc:wlroots
export XDG_CONFIG_DIRS="/etc/xdg/note${XDG_CONFIG_DIRS:+:$XDG_CONFIG_DIRS}:/etc/xdg"
export GTK_USE_PORTAL=1
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM='wayland;xcb'
export SDL_VIDEODRIVER='wayland,x11'
export ELECTRON_OZONE_PLATFORM_HINT=auto
export _JAVA_AWT_WM_NONREPARENTING=1
export LABWC_UPDATE_ACTIVATION_ENV=1

if [ -r "$HOME/.config/environment.d/90-note-locale.conf" ]; then
  set -a
  . "$HOME/.config/environment.d/90-note-locale.conf"
  set +a
fi
[ -r /etc/note-desktop/gpu.conf ] && . /etc/note-desktop/gpu.conf
[ -r "$HOME/.config/note-desktop/gpu.conf" ] && . "$HOME/.config/note-desktop/gpu.conf"

if [ -S "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/bus" ]; then
  export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/bus"
  exec /usr/libexec/note-desktop/note-session-inner
fi
exec dbus-run-session -- /usr/libexec/note-desktop/note-session-inner
