#!/bin/sh
for app in nautilus thunar pcmanfm dolphin; do
  if command -v "$app" >/dev/null 2>&1; then exec "$app"; fi
done
notify-send "Note Desktop" "No hay administrador de archivos instalado"
exit 1
